### ISSUE TITLE
Missing link to "chapter from the excellent interactive NLP course"

### ISSUE THREAD

**Issue by davidefiocco** [osanseviero/hackerllama#5]
In https://github.com/osanseviero/hackerllama/blob/3a52a92d0062df97adb78ed8da199779a43de74d/nbs/blog/posts/sentence_embeddings/index.ipynb#L370 there seems to be a missing link/reference to the course mentioned in the passage

> Understanding the details of word2vec and GloVe is unnecessary to understand the rest of the blog post and sentence embeddings, so I’ll skip them. I recommend reading this chapter from the excellent interactive NLP course if you’re interested.

Thanks for the great blogpost!

**Comment by osanseviero** [comment]
That would be https://lena-voita.github.io/nlp_course/word_embeddings.html !

I'll fix the link. Thanks for raising the issue.
